### ISSUE TITLE
 snyk update check failed, incorrect syntax

### ISSUE THREAD

**Issue by shehackspurple** [clarkio/snyk-cli-action#3]
I added the github action to my workflow and it's telling me the formatting is wrong, PLUS, it's reporting back in my actions that it worked (big green checkmark), so I only noticed it wasn't working because I checked the logs.

Here's a link to my workflow. https://github.com/shehackspurple/dotnetcore-webapp/actions?query=workflow%3A%22.NET+Core%22

End of call error:
snyk update check failed                 │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /github/home/.config

Start of call from Action:
Run clarkio/snyk-cli-action@1.0.0
/usr/bin/docker run --name dfb6583098546074a5c84006bcc961773e2_fa3685 --label 488dfb --workdir /github/workspace --rm -e DOTNET_ROOT -e INPUT_NAME -e INPUT_PATH -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/dotnetcore-webapp/dotnetcore-webapp":"/github/workspace" 488dfb:6583098546074a5c84006bcc961773e2

Thanks in advance for your help!

**Comment by lirantal** [comment]
@shehackspurple can you try working with the more "official" GitHub Actions for Snyk at https://github.com/snyk/actions ? there's documentation there on how to use it too.

**Comment by clarkio** [comment]
Thanks for sharing @lirantal. I'll update the README to point to the official action as this was only created early on when GitHub Actions started to fill the gap before an official one was released.

@shehackspurple does the official one work for you? Can we close this issue?

**Comment by lirantal** [comment]
can wait until Tanya chimes in here herself but yes she pinged me on Twitter DM to confirm that it indeed worked.

**Comment by shehackspurple** [comment]
YES, you can close it.  The official one works great.  Thanks you two!

**Comment by shehackspurple** [comment]
YES, you can close it. The official one works great. Thanks you two!
